apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-2
  labels:
    app.kubernetes.io/name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: http-web-svc
      initContainers:
        - name: init-nginx-service
          image: busybox
          command: ['sh', '-c', "until nslookup nginx-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: nginx-service
#spec:
#  selector:
#    app.kubernetes.io/name: nginx
#  ports:
#    - name: http-nginx-port
#      protocol: TCP
#      port: 2080
#      targetPort: http-web-svc
