apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: app
  labels:
    app.kubernetes.io/name: nginx-multitool
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
      maxSurge: 100%
      maxUnavailable: 80%
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-multitool
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-multitool
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
          name: http-web-svc
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 8080
          name: multitool-8080
        env:
          - name: HTTP_PORT
            value: "8080"
