apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    name: nginx-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-multitool
  template:
    metadata:
      labels:
        name: nginx-multitool
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: http-web-svc
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 8080
          name: multitool-8080
        - containerPort: 8443
          name: multitool-8443
        env:
          - name: HTTP_PORT
            value: "8080"
          - name: HTTPS_PORT
            value: "8443"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-service
spec:
  selector:
    name: nginx-multitool
  ports:
    - name: http-nginx-port
      protocol: TCP
      port: 2080
      targetPort: http-web-svc
    - name: http-multitool-port
      protocol: TCP
      port: 1080
      targetPort: multitool-8080
    - name: https-multitool-port
      protocol: TCP
      port: 1443
      targetPort: multitool-8443
